removed conflicting setting of C++ standard to 11 instead of 14 but running into this:
/microstrain_inertial_driver_common/include/microstrain_inertial_driver_common/services.h:263:83: error: redefinition of default argument for ‘unsigned char DescriptorSet’
  263 | template<typename ServiceType, typename MipType, uint8_t DescriptorSet = MipType::DESCRIPTOR_SET>